#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon May  3 20:48:02 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_OPEN, "", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_SAVE, "", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_SAVEAS, "", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "Check\tCTRL+C", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "Run\tCTRL+R", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_EXIT, "", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "File")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.frame_1_statusbar = self.CreateStatusBar(1, 0)
        
        # Tool Bar
        self.frame_1_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_1_toolbar)
        self.frame_1_toolbar.AddLabelTool(wx.ID_OPEN, "", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        # Tool Bar end
        self.label_1 = wx.StaticText(self, -1, "Positions:")
        self.listboxPositions = wx.ListBox(self, -1, choices=[], style=wx.LB_SINGLE|wx.LB_SORT)
        self.buttonEditPositions = wx.Button(self, -1, "Edit Positions")
        self.textctrlRunlist = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_LINEWRAP)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.openRunlist, id=wx.ID_OPEN)
        self.Bind(wx.EVT_MENU, self.saveRunlist, id=wx.ID_SAVE)
        self.Bind(wx.EVT_MENU, self.saveasRunlist, id=wx.ID_SAVEAS)
        self.Bind(wx.EVT_MENU, self.checkRunlist, id=-1)
        self.Bind(wx.EVT_MENU, self.quitApp, id=wx.ID_EXIT)
        self.Bind(wx.EVT_TOOL, self.openRunlist, id=wx.ID_OPEN)
        self.Bind(wx.EVT_LISTBOX_DCLICK, self.insertPosition, self.listboxPositions)
        self.Bind(wx.EVT_BUTTON, self.edtPositions, self.buttonEditPositions)
        # end wxGlade
        
        self.filename="runlist.py"

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("RobotController")
        self.frame_1_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_1_statusbar_fields = ["frame_1_statusbar"]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        self.frame_1_toolbar.Realize()
        self.textctrlRunlist.SetMinSize((400,400))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.label_1, 0, wx.ALL|wx.EXPAND, 5)
        sizer_3.Add(self.listboxPositions, 1, wx.ALL|wx.EXPAND, 5)
        sizer_3.Add(self.buttonEditPositions, 0, wx.ALL, 5)
        sizer_3.Add((20, 20), 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.ALL|wx.EXPAND, 5)
        sizer_2.Add(self.textctrlRunlist, 2, wx.ALL|wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.ALL|wx.EXPAND, 5)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def edtPositions(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `edtPositions' not implemented!"
        event.Skip()

    def openRunlist(self, event): # wxGlade: MainFrame.<event_handler>

        print "Event handler `openRunlist' not implemented!"
        event.Skip()

    def saveRunlist(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `saveRunlist' not implemented"
        event.Skip()

    def saveasRunlist(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `saveasRunlist' not implemented"
        event.Skip()

    def checkRunlist(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `checkRunlist' not implemented"
        event.Skip()

    def insertPosition(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `insertPosition' not implemented"
        event.Skip()

    def quitApp(self, event): # wxGlade: MainFrame.<event_handler>
        if self.textctrlRunlist.IsModified():
            if wx.MessageBox("Save Runlist?", "Confirm", wx.YES_NO) == wx.YES:
                self.textctrlRunlist.SaveFile(self.filename)

        self.Destroy()

# end of class MainFrame


class RobotController(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = MainFrame(None, -1, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class RobotController

if __name__ == "__main__":
    app = RobotController(0)
    app.MainLoop()
